/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppyd;

/**
 *
 * @author Dell
 */
public class hipercubo extends javax.swing.JFrame {

    /**
     * Creates new form hipercubo
     */
    public hipercubo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emisor = new javax.swing.JComboBox<>();
        destino = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        rutas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        emisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emisorActionPerformed(evt);
            }
        });

        destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        jLabel1.setText("emisor");

        jLabel2.setText("destino");

        jLabel3.setText("ruta a seguir:");

        jTextField3.setEditable(false);

        rutas.setText("Crear ruta");
        rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutasActionPerformed(evt);
            }
        });

        jLabel4.setText("Etiqueta a seguir:");

        jTextField4.setEditable(false);

        jLabel5.setText("(brinco, vertical, diagonal, horizontal)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(rutas))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emisorActionPerformed
        // TODO add your handling code here:
        String cad;
        int aa=emisor.getSelectedIndex();
        llenarE(aa);
        cad=mostrar(A);
        jTextField1.setText(cad);
    }//GEN-LAST:event_emisorActionPerformed

    private void destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoActionPerformed
        // TODO add your handling code here:
        String cad;
        int bb=destino.getSelectedIndex();
        llenarD(bb);
        cad=mostrar(B);
        jTextField2.setText(cad);
    }//GEN-LAST:event_destinoActionPerformed

    public static String mostrar(int[] E){
        String cad;
        cad=E[0]+" "+E[1]+" "+E[2]+" "+E[3];
        return cad;
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed
    private static int[] vv = new int[4];
    private static int[] A = new int[4];
    private static int[] B = new int[4];
    private static String cadena;
    private void rutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutasActionPerformed
        // TODO add your handling code here:
        String cad;
        cadena=" ";
        vv[0]=0;
        vv[1]=0;
        vv[2]=0;
        vv[3]=0;
        int ii=emisor.getSelectedIndex();
        System.out.println(ii);
        vv=oper(A,B);
        cad = mostrar(vv);
        jTextField4.setText(cad);
       switch(ii){
            case 0:
                cero(vv);
                break;
            case 1:
               uno(vv);
                break;
            case 2:
                dos(vv);
                break;
            case 3:
               tres(vv);
                break;
            case 4:
                cuatro(vv);
                break;
            case 5:
                cinco(vv);
                break;
            case 6:
                seis(vv);
                break;
            case 7:
                siete(vv);
                break;
            case 8:
                ocho(vv);
                break;
            case 9:
                nueve(vv);
                break;
            case 10:
                diez(vv);
                break;
            case 11:
                once(vv);
                break;
            case 12:
               doce(vv);
                break;
            case 13:
                trece(vv);
                break;
            case 14:
                catorce(vv);
                break;
            case 15:
                quince(vv);
                break;
        }
       jTextField3.setText(cadena);
    }//GEN-LAST:event_rutasActionPerformed
    
    public static void cero(int[] y){
        cadena= cadena + " 0 ";
        if (y[3]==1) {
            y[3]=0;
            
            uno(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                dos(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    cuatro(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        ocho(y);
                    } else {
                        System.out.println("Llego a su destino 0");
                    }
                }
            }
        }
    }
    public static void uno(int[] y){
        cadena= cadena + " 1 ";
        if (y[3]==1) {
            y[3]=0;
            cero(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                tres(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    cinco(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        nueve(y);
                    } else {
                        System.out.println("Llego a su destino 1");
                    }
                }
            }
        }
    }
    public static void dos(int[] y){
        cadena= cadena + " 2 ";
        if (y[3]==1) {
            y[3]=0;
            tres(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                cero(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    seis(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        diez(y);
                    } else {
                        System.out.println("Llego a su destino 2");
                    }
                }
            }
        }
    }
    public static void tres(int[] y){
        cadena= cadena + " 3 ";
        if (y[3]==1) {
            y[3]=0;
            dos(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                uno(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    siete(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        once(y);
                    } else {
                        System.out.println("Llego a su destino 3");
                    }
                }
            }
        }
    }
    public static void cuatro(int[] y){
        cadena= cadena + " 4 ";
        if (y[3]==1) {
            y[3]=0;
            cinco(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                seis(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    cero(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        doce(y);
                    } else {
                        System.out.println("Llego a su destino 4");
                    }
                }
            }
        }
    }
    public static void cinco(int[] y){
        cadena= cadena + " 5 ";
        if (y[3]==1) {
            y[3]=0;
            cuatro(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                siete(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    uno(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        trece(y);
                    } else {
                        System.out.println("Llego a su destino 5");
                    }
                }
            }
        }
    }
    public static void seis(int[] y){
        cadena= cadena + " 6 ";
        if (y[3]==1) {
            y[3]=0;
            siete(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                cuatro(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    dos(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        catorce(y);
                    } else {
                        System.out.println("Llego a su destino 6");
                    }
                }
            }
        }
    }
    public static void siete(int[] y){
        cadena= cadena + " 7 ";
        if (y[3]==1) {
            y[3]=0;
            seis(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                cinco(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    tres(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        quince(y);
                    } else {
                        System.out.println("Llego a su destino 7");
                    }
                }
            }
        }
    }
    public static void ocho(int[] y){
        cadena= cadena + " 8 ";
        if (y[3]==1) {
            y[3]=0;
            nueve(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                diez(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    doce(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        cero(y);
                    } else {
                        System.out.println("Llego a su destino 8");
                    }
                }
            }
        }
    }
    public static void nueve(int[] y){
        cadena= cadena + " 9 ";
        if (y[3]==1) {
            y[3]=0;
            ocho(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                once(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    trece(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        uno(y);
                    } else {
                        System.out.println("Llego a su destino 9");
                    }
                }
            }
        }
    }
    public static void diez(int[] y){
        cadena= cadena + " 10 ";
        if (y[3]==1) {
            y[3]=0;
            once(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                ocho(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    catorce(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        dos(y);
                    } else {
                        System.out.println("Llego a su destino 10");
                    }
                }
            }
        }
    }
    public static void once(int[] y){
        cadena= cadena + " 11 ";
        if (y[3]==1) {
            y[3]=0;
            diez(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                nueve(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    quince(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        tres(y);
                    } else {
                        System.out.println("Llego a su destino 11");
                    }
                }
            }
        }
    }
    public static void doce(int[] y){
        cadena= cadena + " 12 ";
        if (y[3]==1) {
            y[3]=0;
            trece(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                catorce(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    ocho(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        cuatro(y);
                    } else {
                        System.out.println("Llego a su destino 12");
                    }
                }
            }
        }
    }
    public static void trece(int[] y){
        cadena= cadena + " 13 ";
        if (y[3]==1) {
            y[3]=0;
            doce(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                quince(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    nueve(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        cinco(y);
                    } else {
                        System.out.println("Llego a su destino 13");
                    }
                }
            }
        }
    }
    public static void catorce(int[] y){
        cadena= cadena + " 14 ";
        if (y[3]==1) {
            y[3]=0;
            quince(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                doce(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    diez(y);
                } else {
                    if (y[0]==1) {
                        y[0]=0;
                        seis(y);
                    } else {
                        System.out.println("Llego a su destino 14");
                    }
                }
            }
        }
    }
    public static void quince(int[] y){
        cadena= cadena + " 15 ";
    if (y[3]==1) {
        y[3]=0;
            catorce(y);
        } else {
            if (y[2]==1) {
                y[2]=0;
                trece(y);
            } else{
                if (y[1]==1) {
                    y[1]=0;
                    once(y);
                } else {
                    if (y[0]==1) {
                       y[0]=0;
                        siete(y);
                    } else {
                        System.out.println("Llego a su destino 15");
                    }
                }
            }
        }
    }
    public static int[] oper (int[] e, int[] d){
        int[] ff = new int[4];
        for (int i = 0; i < 4; i++) {
            if (e[i]==d[i]) {
                ff[i]=0;
            } else {
                ff[i]=1;
            }
        }
        return ff;
    }
    public static void llenarE (int ee){
         switch(ee){
            case 0:
                A[0]=0;
                A[1]=0;
                A[2]=0;
                A[3]=0;
                break;
            case 1:
                A[0]=0;
                A[1]=0;
                A[2]=0;
                A[3]=1;
                break;
            case 2:
                A[0]=0;
                A[1]=0;
                A[2]=1;
                A[3]=0;
                break;
            case 3:
                A[0]=0;
                A[1]=0;
                A[2]=1;
                A[3]=1;
                break;
            case 4:
                A[0]=0;
                A[1]=1;
                A[2]=0;
                A[3]=0;
                break;
            case 5:
                A[0]=0;
                A[1]=1;
                A[2]=0;
                A[3]=1;
                break;
            case 6:
                A[0]=0;
                A[1]=1;
                A[2]=1;
                A[3]=0;
                break;
            case 7:
                A[0]=0;
                A[1]=1;
                A[2]=1;
                A[3]=1;
                break;
            case 8:
                A[0]=1;
                A[1]=0;
                A[2]=0;
                A[3]=0;
                break;
            case 9:
                A[0]=1;
                A[1]=0;
                A[2]=0;
                A[3]=1;
                break;
            case 10:
                A[0]=1;
                A[1]=0;
                A[2]=1;
                A[3]=0;
                break;
            case 11:
                A[0]=1;
                A[1]=0;
                A[2]=1;
                A[3]=1;
                break;
            case 12:
                A[0]=1;
                A[1]=1;
                A[2]=0;
                A[3]=0;
                break;
            case 13:
                A[0]=1;
                A[1]=1;
                A[2]=0;
                A[3]=1;
                break;
            case 14:
                A[0]=1;
                A[1]=1;
                A[2]=1;
                A[3]=0;
                break;
            case 15:
                A[0]=1;
                A[1]=1;
                A[2]=1;
                A[3]=1;
                break;
        }
        
    }
    public static void llenarD (int dd){
        switch(dd){
            case 0:
                B[0]=0;
                B[1]=0;
                B[2]=0;
                B[3]=0;
                break;
            case 1:
                B[0]=0;
                B[1]=0;
                B[2]=0;
                B[3]=1;
                break;
            case 2:
                B[0]=0;
                B[1]=0;
                B[2]=1;
                B[3]=0;
                break;
            case 3:
                B[0]=0;
                B[1]=0;
                B[2]=1;
                B[3]=1;
                break;
            case 4:
                B[0]=0;
                B[1]=1;
                B[2]=0;
                B[3]=0;
                break;
            case 5:
                B[0]=0;
                B[1]=1;
                B[2]=0;
                B[3]=1;
                break;
            case 6:
                B[0]=0;
                B[1]=1;
                B[2]=1;
                B[3]=0;
                break;
            case 7:
                B[0]=0;
                B[1]=1;
                B[2]=1;
                B[3]=1;
                break;
            case 8:
                B[0]=1;
                B[1]=0;
                B[2]=0;
                B[3]=0;
                break;
            case 9:
                B[0]=1;
                B[1]=0;
                B[2]=0;
                B[3]=1;
                break;
            case 10:
                B[0]=1;
                B[1]=0;
                B[2]=1;
                B[3]=0;
                break;
            case 11:
                B[0]=1;
                B[1]=0;
                B[2]=1;
                B[3]=1;
                break;
            case 12:
                B[0]=1;
                B[1]=1;
                B[2]=0;
                B[3]=0;
                break;
            case 13:
                B[0]=1;
                B[1]=1;
                B[2]=0;
                B[3]=1;
                break;
            case 14:
                B[0]=1;
                B[1]=1;
                B[2]=1;
                B[3]=0;
                break;
            case 15:
                B[0]=1;
                B[1]=1;
                B[2]=1;
                B[3]=1;
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hipercubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hipercubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hipercubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hipercubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hipercubo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destino;
    private javax.swing.JComboBox<String> emisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton rutas;
    // End of variables declaration//GEN-END:variables
}
